### ISSUE TITLE
The API fails if the title doesn't match when searching a movie

### ISSUE THREAD

**Issue by 00010216** [gammanc/movierecommender#2]
When searching a title  if its misspelled for example :
Correct movie title: "Schindler's List"
Input: "Schindler's Lis"

Server response:
![image_2020-07-13_18-07-37](https://user-images.githubusercontent.com/37200781/87366137-3452c680-c535-11ea-8356-85f4e5c604ff.png)

**Comment by kevinlopeza** [comment]
The function `get_recommendations` now returns an empty dictionary if the title is not found.
